variables:
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
  CRAN: 'https://cloud.r-project.org'

resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: tidymodels

jobs:
  - job: 'Linux'
    variables:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
      TZ: UTC
      CI: true
      KERAS_BACKEND: 'tensorflow'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        #R-3.4:
          #containerImage: rstudio/r-base:3.4-xenial
        #R-3.5:
          #containerImage: rstudio/r-base:3.5-xenial
        R-3.6:
          containerImage: rstudio/r-base:3.6-xenial
    container: $[ variables['containerImage'] ]
    steps:
      - template: templates/r-setup-linux.yml@r-azure-pipelines
      - template: templates/pkg-library.yml@r-azure-pipelines
      - script: sudo apt-get -y install libnlopt-dev
        displayName: 'Install libnlopt'
      - template: templates/pkg-install_dependencies.yml@r-azure-pipelines
      - script: sudo apt-get -y install python3 python3-pip python3-venv
        displayName: 'Install python tools'
      - script: pip3 install keras h5py pyyaml requests Pillow scipy theano
        displayName: 'Install python packages'
      - script: R -e 'install.packages("tensorflow")' -e 'tensorflow::install_tensorflow()'
        displayName: 'Install tensorflow'
      - template: templates/pkg-rcmd_check.yml@r-azure-pipelines
      - template: templates/pkg-coverage.yml@r-azure-pipelines
        parameters:
          coverage: false
